version: "3"
 
services:
  db:
#    image: Dockerfileから立ち上げるときは不要
    container_name: "db"
    build: ./PostgreSQL/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=food
#      全てのホストからアクセス許可。本番では絞る。
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./PostgreSQL/init:/docker-entrypoint-initdb.d
    networks:
      - app-net

  api:
    # db起動後に立ち上げる
    depends_on:
        - db
    links:
        - db:db
    container_name: "api"
    build: ./FastAPI/
    restart: always
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./src:/server
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

